image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

stages:
  - test

test:
  stage: test
  script:
    - apk add docker-compose
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker exec circle-fpm cp .env.example .env
    - docker exec circle-fpm composer install
    - docker ps
#    - docker exec circle-fpm php artisan migrate
    - docker exec circle-fpm vendor/bin/phpunit .

