image: php:7.4

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install & setup drivers
- docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/
- docker-php-ext-install -j$(nproc) gd pdo mbstring pdo_mysql exif pcntl zip bcmath
- pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis
- pecl install pcov && docker-php-ext-enable pcov

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

run-unit-tests:
  script:
  - vendor/bin/phpunit --coverage-text

