image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

stages:
  - build
  - test

build-containers:
  stage: build
  script:
    - apk add docker-compose
    - docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
    - docker exec --tty circle-fpm bash
    - cp .env.example .env
    - composer intall
    - npm i && npm run dev
    - php artisan migrate

run-tests:
  stage: test
  script:
    - docker exec --tty circle-fpm bash
    - vendor/bin/phpunit .

